In [1]:
import numpy as np

In [38]:
def rgb(n):
    '''
    docstring
    random value generator RGB Image array
    '''
    return np.random.randint(255,size=(3,n,n))
    
    

In [39]:
rgb(10)

array([[[254, 101, 166, 151, 241, 238, 103, 114,  52, 131],
        [ 64, 252, 234, 113,  81,  84,  31,  89, 243, 195],
        [ 23,  63,  83, 108,  11, 131, 102, 132, 107, 107],
        [228, 254,  30,  94, 216, 127, 221, 248, 181,  33],
        [ 62, 153, 234,  14, 117,  36, 244,  61, 196, 217],
        [246, 139,   9, 178, 216, 172, 143,   9, 215, 140],
        [ 57, 216, 188,  27, 188, 133, 215, 230, 131,  59],
        [ 29, 190, 127, 178,   4,  57,  12,  90, 245,  51],
        [101, 254,  36,  38,  47,  38,  74,  25, 221,  73],
        [220,  51,  77, 250, 165, 244,  37, 203,  72, 252]],

       [[  0, 224, 243, 170,  29,  41, 195, 152,  72, 184],
        [105,  29,  64, 115, 167,  62,  58,  52, 128, 176],
        [131,   7, 138, 230,  80, 200, 195, 239, 185, 232],
        [ 88,  30, 118,  23, 230,  65, 163, 180,  87,  75],
        [ 64,  43,  65,  19, 159, 157,   8, 147,  10,   6],
        [219, 163,  43,  98, 191,  44,  19,  48, 101,  17],
        [254,  71,  40,  43, 128, 156,

In [40]:
def rubik(n):
    return np.random.random((n,n,n))

In [41]:
rubik(3)

array([[[0.61088865, 0.5414719 , 0.31489202],
        [0.39927772, 0.61824611, 0.21866298],
        [0.59860905, 0.84886105, 0.15025285]],

       [[0.69864088, 0.57936507, 0.59127567],
        [0.21213915, 0.83647688, 0.49510131],
        [0.27455018, 0.07283317, 0.73119942]],

       [[0.78993512, 0.1537515 , 0.11518034],
        [0.40565617, 0.3610492 , 0.40026073],
        [0.86416372, 0.40580607, 0.11774501]]])

In [42]:
def split(records_number):
    #generate data
    data = np.random.random((records_number,np.random.randint(5,10)))
    train_rows = round(0.8*records_number)    
    return data[0:train_rows+1,:],data[train_rows:records_number+1,:]

In [43]:
split(4)

(array([[0.34448101, 0.18822353, 0.71677174, 0.93548926, 0.53762052,
         0.6059178 , 0.51827398, 0.83926247, 0.06018829],
        [0.57919924, 0.05070721, 0.82455903, 0.2543162 , 0.03215872,
         0.26222178, 0.30012155, 0.83369163, 0.13980542],
        [0.95301528, 0.18183426, 0.19476804, 0.58569676, 0.15598168,
         0.15575697, 0.2595718 , 0.88541225, 0.33310995],
        [0.27785215, 0.0400831 , 0.45939455, 0.460495  , 0.35037549,
         0.94080697, 0.07330464, 0.11275225, 0.28341023]]),
 array([[0.27785215, 0.0400831 , 0.45939455, 0.460495  , 0.35037549,
         0.94080697, 0.07330464, 0.11275225, 0.28341023]]))

In [85]:
def mse(arr):
    mse = (np.sum(np.square(arr[:,0],arr[:,1])))/len(arr)
    return mse

In [103]:
data = np.random.randint(10,size=(10,2))
data

array([[8, 7],
       [1, 2],
       [1, 3],
       [8, 5],
       [4, 1],
       [3, 2],
       [0, 1],
       [7, 0],
       [3, 9],
       [7, 2]])

In [104]:
mse(data)

26.2

In [105]:
def mae(arr):
    result = np.sum(np.absolute((arr[:,0]-arr[:,1])))/len(arr)
    return result

In [106]:
mae(data)

22.0

In [111]:
data_log = np.random.random((10,2))

In [115]:
data_log

array([[0.01663839, 0.33215557],
       [0.5008243 , 0.70686119],
       [0.86550089, 0.83161295],
       [0.54024   , 0.02864217],
       [0.19384246, 0.15307508],
       [0.19263241, 0.68209697],
       [0.18154707, 0.82609588],
       [0.36722784, 0.41908718],
       [0.23881771, 0.03055314],
       [0.05294316, 0.21204593]])

In [116]:
def cross_entropy(arr):
    result =  (-1*len(arr))*(np.sum((arr[:,0]*np.log(arr[:,1])) + ((1-arr[:,0]) * np.log(1-arr[:,1]))))
    return result

In [117]:
cross_entropy(data_log)

83.24188728064372