# Numpy

## Installing Numpy Packages

In [1]:
!pip3 install numpy

## Importing Numpy

In [2]:
import numpy as np

## Inisialisasi Numpy Array

In [3]:
arr = np.array([0,1,2,3,4,5])
# defining array 1xn with zero values
zeros = np.zeros(10)
# defining array 1xn with ones
ones = np.ones(10)

In [4]:
print(zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


## Numpy Array Arange Value

In [5]:
arr_2 = np.arange(0,10,2)
print(arr_2)

[0 2 4 6 8]


## Numpy Array Manipulation

In [6]:
# Append --> adding new element into numpy array
arr_2_append = np.append(arr_2,[100])
print(arr_2_append)
# delete
arr_2_delete = np.delete(arr_2,1)
print(arr_2_delete)
# sorting element
unsorted_element = np.array([9,2,-1,2,190,129])
sorted_element = np.sort(unsorted_element)
print(sorted_element)

[  0   2   4   6   8 100]
[0 4 6 8]
[ -1   2   2   9 129 190]


## Shape and Size
==========================
1. Shape (mxn) --> tuple --> (baris x kolom)
2. Dimensi --> jumlah axis
3. Size --> jumlah seluruh elemen

In [30]:
M = np.array(
    [
        [1,2],
        [3,4],
    ]
  
)
print(M)
print(M.ndim)
print(M.shape)
print(M.size)

[[[1 2]
  [3 4]]]
3
(1, 2, 2)
4


In [8]:
N = np.array(
    [
        [10,11],
        [12,13]
    ]
)
print(N)
print(N.ndim)
print(N.shape)
print(N.size)

[[10 11]
 [12 13]]
2
(2, 2)
4


## Reshape
=================== <br>
Membuat bentuk array baru tanpa mengubah data, <br>
!! Perhatikan !! <br>
Jumlah elemen sebelum dan sesudah reshape harus sama

In [9]:
arr_reshape = np.arange(10)
# Membuat bentuk array baru dengan dimensi (50,2) --> jumlah elemen harus sama
new_arr_reshape = arr_reshape.reshape(5,2)
print(new_arr_reshape)

# Membuat ke dimensi (2,5)
new_arr_reshape_2 = arr_reshape.reshape(2,5)
print(new_arr_reshape_2)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


## Convert 1D to 2D
<ul>
    <li>Kegunaan : Meningkatkan dimensi array ke dimensi lebih tinggi </li>
    <li>np.newaxis</li>
    <li>np.expand_dims</li>
</ul>

In [10]:
one_dim_arr = np.arange(6)
# Before
print("Before adding new axis")
print(one_dim_arr) 
print(one_dim_arr.shape)


# newaxis
row_vector = one_dim_arr[np.newaxis,:]
col_vector = one_dim_arr[:,np.newaxis]
print("After adding new axis")
print(row_vector) 
print(row_vector.shape)
print("After adding new axis")
print(col_vector) 
print(col_vector.shape)

Before adding new axis
[0 1 2 3 4 5]
(6,)
After adding new axis
[[0 1 2 3 4 5]]
(1, 6)
After adding new axis
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]
(6, 1)


In [11]:
"""
np.expand_dims --> sama seperti np.newaxis, hanya saja axis bisa ditambahkan pada index position sesuai keinginan kita
"""
N = np.array(
    [
        [10,11],
        [12,13]
    ]
)
P = np.expand_dims(N,axis=0)
print(P)
print(P.shape)

[[[10 11]
  [12 13]]]
(1, 2, 2)


## Indexing and Slicing Numpy Array
================================= <br>
Prinsipnya sama seperti slicing dan indexing pada List Python

In [12]:
my_matrix = np.array(
    [
        [1,2,3,4],
        [5,6,7,8],
        [9,10,11,12]
    ]
)
print(my_matrix.shape)
# cetak baris 0 sampai 1
print('Example 1')
print(my_matrix[0:2])
# cetak semua baris
print('Example 2')
print(my_matrix[:])
# cetak kolom kedua
print('Example 3')
print(my_matrix[:,1])
# Carikan semua elemen dalam my_matrix yang kurang dari 10
print('Example 4')
print(my_matrix[my_matrix<10])
# Carikan semua elemen dalam my_matrix yang habis dibagi 2
print('Example 5')
print(my_matrix[my_matrix%2==0])
# Using logic operator
print('Example 6')
print(my_matrix[(my_matrix>2) & (my_matrix<10)])

(3, 4)
Example 1
[[1 2 3 4]
 [5 6 7 8]]
Example 2
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Example 3
[ 2  6 10]
Example 4
[1 2 3 4 5 6 7 8 9]
Example 5
[ 2  4  6  8 10 12]
Example 6
[3 4 5 6 7 8 9]


## Creating Array From Existing Data
np.vstack() --> menumpuk array secara vertikal <br>
np.hstack() --> menumpuk array secara horisontal <br>
np.hsplit() --> membagi array menjadi n ukuran sama besar <br>
.view() --> mengcopy array (shallow copy) <br>
.copy() --> mengcopy array (deep copy)

In [13]:
arr_10 = np.arange(100)
M = np.array(
    [
        [1,2],
        [3,4],
    ]
)
N = np.array(
    [
        [10,11],
        [12,13]
    ]
)

In [14]:
arr_10_new = arr_10[3:80]
print(arr_10_new)

[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26
 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50
 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74
 75 76 77 78 79]


In [15]:
v_stack_M_N = np.vstack((M,N))
h_stack_M_N = np.hstack((M,N))
print(v_stack_M_N)
print(h_stack_M_N)

[[ 1  2]
 [ 3  4]
 [10 11]
 [12 13]]
[[ 1  2 10 11]
 [ 3  4 12 13]]


In [16]:
arr_split_example = np.array(
    [
        np.arange(10),
        np.arange(40,60,2)
    ]
)
# Membagi array menjadi 10 sama besar
arr_splitted = np.hsplit(arr_split_example,10)
print(arr_splitted)

[array([[ 0],
       [40]]), array([[ 1],
       [42]]), array([[ 2],
       [44]]), array([[ 3],
       [46]]), array([[ 4],
       [48]]), array([[ 5],
       [50]]), array([[ 6],
       [52]]), array([[ 7],
       [54]]), array([[ 8],
       [56]]), array([[ 9],
       [58]])]


In [17]:
M_view = M.view()
M_copy = M.copy()
print(M_copy)

[[1 2]
 [3 4]]


## Basic Array Operations 

In [18]:
z = np.arange(0,10)
y = np.arange(10,20)

# Addition
z+y
# Subtraction
z-y
# Multiplication
z*y
# Division
z/y

array([0.        , 0.09090909, 0.16666667, 0.23076923, 0.28571429,
       0.33333333, 0.375     , 0.41176471, 0.44444444, 0.47368421])

In [19]:
# menjumlahkan elemen ke arah baris
print(M_copy.sum(axis=0))
# Menjumlahkan elemen ke arah kolom
print(M_copy.sum(axis=1))
# max
print(M_copy.max())

[4 6]
[3 7]
4


## Matrices

In [20]:
# Defining matrix 3 x 2
matrix = np.array(
    [
        [10,28],
        [290,90],
        [99,2]
    ]
)
# defining random element matrix (3,4)
rand_matrix = np.random.random((3,4))
# Defining matrix identity
identity_matrix = np.ones((3,3))
# Defining zero matrix 
zero_matrix = np.zeros((3,3))

print(matrix)
print(rand_matrix)
print(identity_matrix)
print(zero_matrix)

[[ 10  28]
 [290  90]
 [ 99   2]]
[[0.42318725 0.53587636 0.53165225 0.82176538]
 [0.49543481 0.00945978 0.51911175 0.91629888]
 [0.08682814 0.20066658 0.36913934 0.5503505 ]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


## Matrices Arithmetics Operations

In [21]:
A = np.random.random((4,3))
B = np.random.random((4,3))

C = A+B
D = A-B
E = A/B
F = A*B

print(A)
print(B)
print(C)
print(D)
print(E)
print(F)

[[0.74526285 0.52266205 0.70341728]
 [0.78676758 0.78023501 0.27334114]
 [0.23141836 0.72498323 0.5790177 ]
 [0.0933567  0.38459406 0.99622116]]
[[0.50704223 0.63894958 0.79393901]
 [0.93568526 0.13362401 0.70282558]
 [0.18145252 0.18794887 0.46441322]
 [0.77676541 0.53238618 0.64054774]]
[[1.25230508 1.16161163 1.4973563 ]
 [1.72245284 0.91385901 0.97616672]
 [0.41287089 0.9129321  1.04343092]
 [0.87012211 0.91698024 1.6367689 ]]
[[ 0.23822063 -0.11628754 -0.09052173]
 [-0.14891768  0.646611   -0.42948444]
 [ 0.04996584  0.53703436  0.11460448]
 [-0.68340871 -0.14779211  0.35567343]]
[[1.46982404 0.81800201 0.88598403]
 [0.8408464  5.83903314 0.38891746]
 [1.27536589 3.85734286 1.24677265]
 [0.12018648 0.72239679 1.55526451]]
[[0.37787974 0.3339547  0.55847042]
 [0.73616683 0.10425813 0.19211115]
 [0.04199145 0.13625978 0.26890348]
 [0.07251626 0.20475256 0.63812721]]


In [22]:
"""
dot product matrix
Z --> (3,2)
V --> (2,3)
T = Z dot V = (3,3)
"""
Z = np.array(
    [
        [1,2],
        [2,3],
        [4,5]
    ]
)
V = np.array(
    [
        [1,2,3],
        [4,5,6]
    ]
)
T = np.dot(Z,V)
print(T)
print(T.shape)

[[ 9 12 15]
 [14 19 24]
 [24 33 42]]
(3, 3)


## Tranpose and Reshape Matrices

In [23]:
Z_tranpose = Z.T
print(Z)
print(Z_tranpose)

[[1 2]
 [2 3]
 [4 5]]
[[1 2 4]
 [2 3 5]]


In [25]:
# reshape matrix from (6x1) into (3,2)
data_col = np.arange(6).reshape((3,2))
print(data_col)

[[0 1]
 [2 3]
 [4 5]]


## N Dimensional Array

In [26]:
# N dimensional array (3,2,4)
ndarray = np.array(
    [
        [
            [1,2,4,5],
            [3,4,9,10]
        ],
        [
            [3,4,5,6],
            [5,4,2,1]
        ],
        [
            [45,23,4,6],
            [12,3,4,6]
        ]
    ]
)
print(ndarray)

[[[ 1  2  4  5]
  [ 3  4  9 10]]

 [[ 3  4  5  6]
  [ 5  4  2  1]]

 [[45 23  4  6]
  [12  3  4  6]]]


In [27]:
# Menginisialisasi multi dimensi hanya dengan menambahkan koma sesuai dimensi yang kita inginkan
ndarray_random = np.random.random((3,2,4))
print(ndarray_random)

[[[0.54362625 0.94226911 0.7769806  0.4798924 ]
  [0.33937116 0.68375234 0.73696039 0.91137993]]

 [[0.76634213 0.64659628 0.61350051 0.24060825]
  [0.04461533 0.27632749 0.68200568 0.28579073]]

 [[0.17439327 0.53591054 0.88321288 0.05637605]
  [0.67981193 0.80416474 0.12613616 0.87228693]]]


## Flatten N Dimensional Array
================================== <br>
Meratakan dari dimensi yang lebih tinggi ke dimensi yang lebih rendah

In [28]:
arrflat_random = np.random.random((3,3))
print("Before Flatten")
print(arrflat_random)
print("After Flatten")
arrflat_result = arrflat_random.flatten()
print(arrflat_result)

Before Flatten
[[0.33804514 0.87281613 0.78125551]
 [0.99180664 0.6572508  0.91777944]
 [0.71342139 0.52346297 0.44386832]]
After Flatten
[0.33804514 0.87281613 0.78125551 0.99180664 0.6572508  0.91777944
 0.71342139 0.52346297 0.44386832]
